### ISSUE TITLE
Swift code

### ISSUE THREAD

**Issue by SagarUnagar** [weijentu/automatic-height-tagcells#3]
Is there Swift sample code available for this project?

Thanks in advance! :)

**Comment by weijentu** [comment]
You are welcome. I'll do it once I have enough time :)

**Comment by SagarUnagar** [comment]
@weijentu Thanks much:) Please make it available as soon as earliest.

**Comment by weijentu** [comment]
The latest commit has included Swift 3.0 sample code. Cheers!
