### ISSUE TITLE
Horizontal scrolling for Tableview Cell

### ISSUE THREAD

**Issue by SagarUnagar** [weijentu/automatic-height-tagcells#4]
Hello @weijentu 

Actually, I want a scrollable horizontal cell so that if there is more tag than the height of cell, then it will display you in the next paging screen. So what will be changes require in this current project?

Thanks in a advance!

P.S: I have successfully converted this Obj C code to Swift already. And it's working fine. Thanks!

**Comment by weijentu** [comment]
@SagarUnagar it's little beyond the original purpose of this project. Anyway, if you would like to have a scrollable horizontal cell. I suggest you probably could try to implement a collection view into the UITableViewCell.
