### ISSUE TITLE
Use json for data

### ISSUE THREAD

**Issue by FredvanRijswijk** [weijentu/automatic-height-tagcells#5]
Very good looking project, I figuring out how to use Firebase data or json to populate the tableview / tags, can you give me some direction where and maybe how?

**Comment by weijentu** [comment]
@FredvanRijswijk You are welcome. Once you translate your json data, you can construct AHTags according to the data, and then build up tags into an array. I suggest you can take a look of the relationship between class `AHTag` and array `dataSource` in the `ViewController` class

**Comment by FredvanRijswijk** [comment]
I have the problem that all the tags section have one tag

```
var tags: [Array<AHTag>] = { () -> [Array<AHTag>] in
        return [

            ]
    }()
```

```

let dictionary = snapshot.value as? [String: AnyObject]
            let constD = [AHTag(category: (dictionary?["categorie"]) as? String ?? "Test", name: (dictionary?["name"]) as? String ?? "Test", color: UIColor(hexString: "#663383"), enabled: false)]

            let cat:[AHTag] = constD

            self.tags.append(cat)
```

**Comment by weijentu** [comment]
@FredvanRijswijk I guess you probably didn't notice that `dataSource` in `ViewController` is a form of array in array. In another way, it means you can declare `dataSource` as `[[AHTag]]` as well.

I just committed some changes to demonstrate for working with JSON string in both ObjC & Swift. You may check them in the source code for references.

Cheers,

**Comment by FredvanRijswijk** [comment]
My problem is that I get my data as a dictonary and I make an Array from AHTag but then is my data different as from the original datasource:

```

[[Guides.AHTag(category: "Value", name: "Value", color: UIExtendedSRGBColorSpace 0.584314 0.458824 0.803922 1, enabled: false)], [Guides.AHTag(category: "Value", name: "Value", color: UIExtendedSRGBColorSpace 0.584314 0.458824 0.803922 1, enabled: false)], [Guides.AHTag(category: "Value", name: "Value ", color: UIExtendedSRGBColorSpace 0.584314 0.458824 0.803922 1, enabled: false)], .... ]]


import UIKit
import Firebase

class TagsViewController: UITableViewController {

    var ref: FIRDatabaseReference!
    var _refHandle: FIRDatabaseHandle!

     var tags = [[AHTag]]()

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

        giveMeTags()

    }

    func giveMeTags() {

        ref = FIRDatabase.database().reference()
        _refHandle = ref.child("user-tags").observe(.childAdded, with: { (snapshot) in

            let dictionary = snapshot.value as? [String: AnyObject]

            self.tags.append([AHTag(dictionary: dictionary!)])

            DispatchQueue.main.async(execute: {
                self.tableView.reloadData()
            })

            print(self.tags)


        })

    }


```

What you do with the datasource is like magic to me

**Comment by weijentu** [comment]
@FredvanRijswijk Could you attach your JSON string? According to above code, I guess object for key `"user-tags"` is an array; however; you only add it once in the block with `self.tags.append([AHTag(dictionary: dictionary!)])`
