### ISSUE TITLE
怎么适配ios8系统 cell上的约束在系统8上显示不出来，如何解决？

### ISSUE THREAD

**Issue by shine0007** [weijentu/automatic-height-tagcells#6]

**Comment by weijentu** [comment]
@shine0007  稍早安装了iOS 8 simulator测试，没发现适配上的问题，可以说明更清楚些吗？或是有代码可以参考更好。
<img width="487" alt="screen shot 2016-11-18 at 11 00 50 am" src="https://cloud.githubusercontent.com/assets/8802123/20442661/600cb326-ad7e-11e6-9cfb-02d4a5a5ae3d.png">
