### ISSUE TITLE
Extra separator line for iPhone 6 Plus size device

### ISSUE THREAD

**Issue by anuj77** [weijentu/automatic-height-tagcells#7]
There are some strange separator lines are getting added for **6 plus 7 plus devices only.**
I have just run the demo code and its happening.
![simulator screen shot 31-jan-2017 5 04 07 pm](https://cloud.githubusercontent.com/assets/16817128/22463455/ab3c8978-e7d7-11e6-835b-f5e08cdc43b1.png)

**Comment by weijentu** [comment]
@anuj77 Just got a time to investigate this issue and it's really a strange one. Thanks for reporting this. I'll commit update once I got a solution.

**Comment by MourinhoLove** [comment]
I have Same problem  On 6 plus 7 plus devices only;

**Comment by weijentu** [comment]
@anuj77 @MourinhoLove  Somehow opaque setting for UIGraphicsBeginImageContextWithOptions
solves the issue :) Please check out my latest committed changes.

**Comment by MourinhoLove** [comment]
@weijentu Thank You.This bug has been fixed.

**Comment by anuj77** [comment]
@weijentu thank you for the fix
